### ISSUE TITLE
Stream<User> get authStateChanges => _firebaseAuth.idTokenChanges();

### ISSUE THREAD

**Issue by spider-here** [RobertBrunhage/flutter_firebase_auth_tutorial#2]
![Screenshot from 2021-08-18 06-15-47](https://user-images.githubusercontent.com/87274056/129821052-fdb57e71-b5d1-4948-933b-0028860d172d.png)
![Screenshot from 2021-08-18 06-15-53](https://user-images.githubusercontent.com/87274056/129821055-3620c717-b70d-48e4-baf4-63d0e227c8a4.png)

**Comment by RobertBrunhage** [comment]
The error explains exactly what needs to be done.

instead of:
`Stream<User> authStateChanges => _firebaseAuth.idTokenChanges();`

it would be:
`Stream<User?> authStateChanges => _firebaseAuth.idTokenChanges();`.

Sadly I don't have the time to go over old repositories to refactor them for null-safety so if you or anyone have the time for that, PR's are greatly appreciated!
